joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController

rrbot_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
       - joint1
       - joint2
    write_op_modes:
       - joint1
       - joint2
