joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController

rrbot_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
       - joint1
       - joint2
    write_op_modes:
       - joint1
       - joint2
    state_publish_rate: 25
    action_monitor_rate: 20
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 5
